### ISSUE TITLE
Fatal error: Uncaught TypeError: preg_match()

### ISSUE THREAD

**Issue by ghost** [io-developer/php-whois#220]
**PHP-Whois version**: 4.1.1(latest)

**PHP version**: 8.3

**Description**  
```
PHP Fatal error:  Uncaught TypeError: preg_match(): Argument #2 ($subject) must be of type string, array given in vendor/io-developer/php-whois/src/Iodev/Whois/Modules/Tld/Parsers/BlockParser.php:430
Stack trace:
#0 vendor/io-developer/php-whois/src/Iodev/Whois/Modules/Tld/Parsers/BlockParser.php(430): preg_match()
#1 vendor/io-developer/php-whois/src/Iodev/Whois/Modules/Tld/Parsers/BlockParser.php(364): Iodev\Whois\Modules\Tld\Parsers\BlockParser->parseDate()
#2 vendor/io-developer/php-whois/src/Iodev/Whois/Modules/Tld/Parsers/BlockParser.php(116): Iodev\Whois\Modules\Tld\Parsers\BlockParser->parseCreationDate()
#3 vendor/io-developer/php-whois/src/Iodev/Whois/Modules/Tld/Parsers/AutoParser.php(72): Iodev\Whois\Modules\Tld\Parsers\BlockParser->parseResponse()
#4 vendor/io-developer/php-whois/src/Iodev/Whois/Modules/Tld/TldModule.php(204): Iodev\Whois\Modules\Tld\Parsers\AutoParser->parseResponse()
#5 vendor/io-developer/php-whois/src/Iodev/Whois/Modules/Tld/TldModule.php(178): Iodev\Whois\Modules\Tld\TldModule->loadParsedTo()
#6 vendor/io-developer/php-whois/src/Iodev/Whois/Modules/Tld/TldModule.php(137): Iodev\Whois\Modules\Tld\TldModule->loadDomainData()
#7 vendor/io-developer/php-whois/src/Iodev/Whois/Whois.php(119): Iodev\Whois\Modules\Tld\TldModule->loadDomainInfo()
#8 tld.php(206): Iodev\Whois\Whois->loadDomainInfo()
#9 {main}
  thrown in vendor/io-developer/php-whois/src/Iodev/Whois/Modules/Tld/Parsers/BlockParser.php on line 430

```

**How to reproduce**  
Absolutely No idea! I'm doing >100k scans and this issue has only popped up less than ten times. Sadly, I did Not capture what domain, what TLD this error occurred on. All I can say, is that it was a ccTLD

**Possible Solution**  
How to fix the root issue? No idea!
How to potentially slap a bandaid on it? (untested)
` && is_string($str)` in ` if ($str && is_string($str) && preg_match($fallbackRegex, $str)) {` (BlockParser.php:430)

**Additional context**  
N/a

**Comment by decadence** [comment]
I got `preg_match(): Argument #2 ($subject) must be of type string, array given` with domain `herbalife.by`

**Comment by dmachehin** [comment]
![Image](https://github.com/user-attachments/assets/7c154a2f-1eaa-4f98-86ec-36976a6242f3)

**Comment by Grendel7** [comment]
I ran into the same error, and I think I found more about what triggers this.

The issue is that sometimes the WHOIS output contains the same key multiple times in places where it's not expected.

One particular domain name I had this issue with had WHOIS output looking like this:

```
Registrant Name: John Doe
Registrant Organization: n/a
Registrant Street: Example Street 420
Registrant Street: Apt. 42
Registrant Street: 
Registrant City: Testertown
```

The `ParserHelper::linesToGroups` function turns this structure into something like this (formatted as YAML here):

```yaml
Registrant Name: John Doe
Registrant Organization: n/a
Registrant Street: 
- Example Street 420
- Apt. 42
- ""
Registrant City: Testertown
```

Turning duplicate keys into an array is more or less expected, because duplicate keys are common and sometimes different, and then all values are relevant (i.e. the `Name Server` key).

The date parser assumes that all keys it gets are single keys, but that's not the case here, and that's what causes it to break.
